# Travis CI configuration file for psycopg2

dist: trusty
sudo: required
language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6-dev

install:
  - python setup.py install

script:
  - sudo scripts/travis_prepare.sh
  - scripts/travis_test.sh


notifications:
  email: false
