language: python

services:
  - postgresql

addons:
    postgresql: 9.4

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6-dev

before_script:
  - psql -c 'create database psycopg2_test;' -U postgres
  - psql -c 'create extension hstore;' -U postgres

install:
  - python setup.py install

script: make check


notifications:
  email: false
